AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM setup for local testing

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  PrintRiderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dev.deskriders.printrider.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: ../build/distributions/print-rider-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
