AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM setup for local testing

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  PrintRiderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dev.deskriders.printrider.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: ../build/distributions/print-rider-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Environment:
        Variables:
          APP_DOMAIN_NAME: "http://localhost:8080"
          APP_PRINT_DOCUMENTS_DB_TABLE: "local-print-documents"
          APP_DYNAMO: "http://dynamo:8000"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
