AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS PrintRider API - dev.deskriders.printrider::print-rider
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  PrintRiderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dev.deskriders.printrider.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: build/distributions/print-rider-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  PrintDocumentsDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: DocId
          AttributeType: S
      KeySchema:
        - AttributeName: DocId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: PrintDocuments

Outputs:
  PrintRiderApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: PrintRiderApi
